apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: task-service
  labels:
    app: task-service
spec:                                                # 3
  containers:
    - image: bhanuchaddha/task-service:latest # 4
      name: task-service                              # 5
      ports:
        - containerPort: 6543

---
apiVersion: v1
kind: Service              # 1
metadata:
  name: task-service-lb
spec:
  type: LoadBalancer       # 2
  ports:
    - port: 6543               # 3
      protocol: TCP          # 4
      targetPort: 6543         # 5
  selector:                # 6
    app: task-service

---
apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: task-service
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: task-service                                 # 7
    spec:
      containers:
        - image: bhanuchaddha/task-service:latest
          imagePullPolicy: Always                         # 8
          name: task-service
          ports:
            - containerPort: 6543