apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: knapsack-service
  name: knapsack-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: knapsack-service
    spec:
      containers:
      - env:
        - name: KAFKA_URL
          value: kafka:9092
        - name: MONGODB_URI
          value: mongodb://database:27017/mydb
        image: bhanuchaddha/knapsack-service:latest
        name: knapsack-service
        resources: {}
      restartPolicy: Always
status: {}
